### ISSUE TITLE
Origin and Destination Areas expect node in center

### ISSUE THREAD

**Issue by jugdemon** [tumcms/MomenTUM#8]
I am now looking at the results of the simulation (#7 not withstanding) and I noticed the agents do not move at all. After checking the CSV file this seems to be case. Upon inspection of the visualisation I notice that agents get spawned in the center of the area instead of the nodes within the area. It seems that `insideAreaSeed` only holds for `Intermediate`, but not for `Origin` and possibly not for `Destination` either.

**Comment by jugdemon** [comment]
In particular, the function `calculateFreeSpawnPositions` in `PointGeneratorGeometry` uses the center of the `Area` which in my case is not connected to the grid.

Shall I go for a work-around, where `Origin` and `Destination` are connected to the grid, or is there a reasonable way to alter this to use graph vertices within the Area? I am not familiar enough with the code to judge this.

**Comment by PeterMKielar** [comment]
@jugdemon
I’m not sure what your issue is here.
Thus, a general instruction:
Origin are the only areas where pedestrian are generated if you use a generator model.
There are different generator models and if you use a Point generator geometry type they will spawn in the center of the origin area.
You may like to use a random lattice geometry here. It will randomly generate pedestrians inside an origin area. See:
momentum-documentation\UserGuide\Explanations\NonBehaviorModelExamples\generatorExamples.xml
E.g.:
`<generator id="1" name="generatorPlan" type="Plan" scenario="0" origin="1" seed="0">`
`…`
`<geometry geometryType="Lattice"/>`
`<property name="scenarioLatticeId" type="Integer" value="0"/>`
`…`
You have to be careful to identify the cause-and-effect relationships:
The graph model in the configuration focuses on graph operations (e.g. reading a graph from a layout and put it into the simulation, FromGraphOperation). Generating pedestrians is the task of generator models. Thus, the insideAreaSeed is of the FromGraphOperation will just find a vertex inside any area that is given in the layout and associate it with the area’s geometry. This is independent of the pedestrian generation.

Your pedestrian do not move? This is mostly cause by issues in the tactical/routing configuration, the routing model itself, or a missing vertex/edge in the graph.
Check the following:
- Is your graph connected to the area where the pedestrians will spawn and will walk to (origin and destination are connected).

- Is your model compatible with given tactical properties? You might deactivate tactical control and routeMemory (remember the visited vertices). 
`<tactical id="4" name="tactical" perceptualModel="0">`
`…`
`<property name="routeMemory" type="Boolean" value="False" />`
`<property name="tacticalControl" type="Boolean" value="False" />`
`</tactical>`
- Is your graph model correctly initialized (if you use a Dijkstra based method, check for weights and so on).
- Exchange your routing model with another one (Dijkstra) and set the tactical properties to false. Does this work?
